## Setting

### Importing Dependencies

In [10]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\jjska\anaconda3\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\jjska\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\users\jjska\anaconda3\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\jjska\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in c:\users\jjska\anaconda3\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\jjska\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [106]:
import pandas as pd

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score

from wordcloud import WordCloud

import matplotlib.pyplot as plt

In [108]:
nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

stemmer = PorterStemmer()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jjska\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\jjska\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

### Data Load & Cleaning

In [98]:
data = pd.read_csv("pilot_textming.csv")
data.head()

,Title,Keywords,Abstract
0,The development for Internet of Things smart h...,IoT; smart home; service; platform,Internet of things smart home integrates autom...
1,Service Provisioning Framework for Digital Sma...,smart home; service provisioning; distributed ...,Development and Management Framework of Smart ...
2,SHSM: A Service Middleware for Smart Home,Smart Home; Service Middleware; Service Comput...,There emerges an increasing need to overcome t...
3,SDN-based multi-level framework for smart home...,SDN; Smart home API; Smart services; Smart hom...,The smart home is a field that uses smart devi...
4,Privacy-Aware Web Services in Smart Homes,Policy; Privacy; Smart Home; Trust; Web service,Smart homes can assist their inhabitants with ...

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Title     1000 non-null   object
 1   Keywords  959 non-null    object
 2   Abstract  999 non-null    object
dtypes: object(3)
memory usage: 23.6+ KB

In [99]:
data.dropna(subset=['Abstract'], inplace=True)
data.drop_duplicates(subset=['Title'], inplace=True)

In [100]:
data.shape

(998, 3)

In [101]:
def combine_2rd_columns(col_1, col_2, col_3):
    result = col_1
    if not pd.isna(col_2):
        result += " " + str(col_2)
    return result


data = pd.read_csv("pilot_textming.csv")
data["text"] = data.apply(lambda x: combine_2rd_columns(x['Title'], x['Keywords'], x['Abstract']), axis=1)

df = data.loc[:, ['text']]
df.head()

                                                text
0  The development for Internet of Things smart h...
1  Service Provisioning Framework for Digital Sma...
2  SHSM: A Service Middleware for Smart Home Smar...
3  SDN-based multi-level framework for smart home...
4  Privacy-Aware Web Services in Smart Homes Poli...

#### Data Preprocess

In [102]:
def preprocess_text(text):
    # 소문자 변환 및 토큰화 (단어 단위로 분할)
    tokens = text.lower().split()
    
    # Stopword 제거 및 Lemmatization 수행
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token) for token in tokens if token not in stop_words]
    
    # Stemming 수행 (Porter Stemmer 사용)
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(token) for token in tokens]
    
    # 숫자 제거 및 재결합하여 문자열 반환
    processed_text = ' '.join([token for token in tokens if not token.isdigit()])
    
    return processed_text

df['processed_text'] = df['text'].apply(preprocess_text)
df = df.loc[:, ['processed_text']]
df.head()

                                      processed_text
0  develop internet thing smart home servic oper ...
1  servic provis framework digit smart home servi...
2  shsm: servic middlewar smart home smart home; ...
3  sdn-base multi-level framework smart home serv...
4  privacy-awar web servic smart home policy; pri...

In [103]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(df['processed_text'])
tfidf_matrix

<1000x2406 sparse matrix of type '<class 'numpy.float64'>'
	with 14430 stored elements in Compressed Sparse Row format>

#### Selected only the word-features - based on TF-IDF(Python scikit-Learn Library)

In [109]:
# 상위 Docuement 당 TF-IDF 기반 상위 4개의 단어 추출 함수 정의

top_keywords_per_document = []
feature_names = vectorizer.get_feature_names_out()

for i in range(len(df)):
    tfidf_scores = zip(feature_names, tfidf_matrix[i].toarray()[0])
    sorted_tfidf_scores = sorted(tfidf_scores,key=lambda x: x[1], reverse=True)
    top_keywords_per_document.append([keyword for keyword,_ in sorted_tfidf_scores[:4]])

# 전체 데이터셋에서 적어도 2번 이상 나온 키워드 추출하기 
all_keywords=[keyword for document in top_keywords_per_document for keyword in document]
selected_keywords=list(set(keyword for keyword in all_keywords if all_keywords.count(keyword) >=2))

# 선택된 키워드를 기반으로 Document-Term Matrix 생성
vectorizer=CountVectorizer(vocabulary=selected_keywords)
document_term_matrix=vectorizer.fit_transform(df['processed_text'])

# WordCloud 시각화 함수 정의 및 실행   
def visualize_wordcloud(keywords):
     wordcloud=WordCloud(background_color='white', width=800,height=400).generate(' '.join(keywords))
     plt.imshow(wordcloud.recolor(colormap='viridis',random_state=42),interpolation="bilinear")
     plt.axis("off")
     plt.show()

visualize_wordcloud(selected_keywords)
document_term_matrix

NotFittedError: Vocabulary not fitted or provided

In [89]:
# 재정규화된 TF-IDF 값으로 단어 분포 확인

renormalized_tfidf_matrix = tfidf_matrix / tfidf_matrix.sum(axis=1)
word_distribution_per_document = renormalized_tfidf_matrix.toarray()

print("\nWord Distribution per Document:")
for i in range(len(df)):
    print(f"Document {i+1}:")
    word_distribution_pairs = zip(feature_names, word_distribution_per_document[i])
    sorted_word_distribution_pairs = sorted(word_distribution_pairs,key=lambda x: x[1], reverse=True)
    
    for word,distribution in sorted_word_distribution_pairs:
        print(f"{word}: {distribution}")

AttributeError: 'matrix' object has no attribute 'toarray'